[package]
name = "mouse-mover"
version = "0.2.0"
authors = ["Bob Qi <baobin.qi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mouse-rs = "0.3"
structopt = "0.3"
